---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: echo
    spec:
      restartPolicy: Always

      containers:
        - name: echo
          image: eu.gcr.io/wire-bot/echo:latest

          resources:
            requests:
              memory: "50Mi"
            limits:
              memory: "500Mi"

          env:
            - name: DATA_DIR
              value: "/var/lib/echo"

            - name: KEYSTORE_FILE
              value: "/var/lib/echo/keystore.jks"

            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: echo-knows
                  key: token

            - name: KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: echo-knows
                  key: keystore_password

          volumeMounts:
            - name: echo-disk
              mountPath: /var/lib/echo

            - name: echo-config
              mountPath: /etc/echo

          command:
            - "/bin/bash"
            - "-c"
            - "base64 --decode -i /etc/echo/keystore.jks.base64 > $(KEYSTORE_FILE)
            && /usr/bin/java
            -Ddw.server.applicationConnectors[1].keyStorePassword=$(KEYSTORE_PASSWORD)
            -Ddw.server.applicationConnectors[1].keyStorePath=$(KEYSTORE_FILE)
            -Ddw.auth=$(TOKEN)
            -Ddw.cryptoDir=$(DATA_DIR)
            -jar echo.jar server /etc/echo/echo.yaml"

      volumes:
        - name: echo-disk
          gcePersistentDisk:
            pdName: echo-disk
            fsType: ext4

        - name: echo-config
          configMap:
            name: echo-config

---
apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  selector:
    name: echo
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      targetPort: 4443
      protocol: TCP