---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: echo
    spec:
      restartPolicy: Always

      containers:
        - name: echo
          image: eu.gcr.io/wire-bot/echo:latest

          resources:
            requests:
              memory: "50Mi"
            limits:
              memory: "500Mi"

          env:
            - name: DATA_DIR
              value: "/var/lib/echo"

            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: echo-knows
                  key: token

          ports:
            - containerPort: 8080
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /bots/status
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 30
            periodSeconds: 10

          # for L7 LB
          readinessProbe:
            httpGet:
              path: /bots/status
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 30

          volumeMounts:
            - name: echo-disk
              mountPath: /var/lib/echo

            - name: echo-config
              mountPath: /etc/echo

          command:
            - "/usr/bin/java"
            - "-Ddw.cryptoDir=$(DATA_DIR)"
            - "-Ddw.auth=$(TOKEN)"
            - "-Denv=staging"
            - "-jar"
            - "echo.jar"
            - "server"
            - "/etc/echo/echo.yaml"
          
      volumes:
        - name: echo-disk
          gcePersistentDisk:
            pdName: echo-disk
            fsType: ext4

        - name: echo-config
          configMap:
            name: echo-config

---
apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  selector:
    name: echo
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP